package edu.byui.maddldsdj;


public class User {
    // variables to identify users
    private String userEmail;
    private String userID;
    private boolean isAdmin;

    /**
     * The User class stores information for the user
     * when they sign into the app.
     * <p>
     * @author Dallas Bleak
     * @since 2017-06-01
     */
    public User() {
        userEmail = "none";
        userID = "none";
        isAdmin = false;
    }

    /**
     * Creates a user with a user specified email and then sets the user ID from
     * Firebase which returns the user ID after the uer registers, and sets the
     * admin status to false.
     * @param email generated by the user
     * @param uid generated by Firebase
     */
    public User(String email, String uid) {
        this.userEmail = email;
        this.userID = uid;
        this.isAdmin = false;
    }

    /**
     * Creates a user with a user specified email and then sets the user ID from
     * Firebase which returns the user ID after the uer registers, and sets the
     * admin status from the Firebase databse.
     * @param email generated by the user
     * @param uid generated by Firebase
     * @param admin retrieved from Firebase database
     */
    public User(String email, String uid, boolean admin) {
        this.userEmail = email;
        this.userID = uid;
        this.isAdmin = admin;
    }

    public String getUserEmail() {
        return userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public boolean isAdmin() {
        return isAdmin;
    }

    public void setAdmin(boolean admin) {
        isAdmin = admin;
    }
}
